
import javax.swing.DefaultListModel;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20107나호겸
 */
public class MainFrame extends javax.swing.JFrame {
    public static ContainerClient containerClient;
    public static AlarmPanel ap;
    public static GraphPanel gp1;
    public static SearchPanel sp;
    public static GraphPanel gp2;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        ap = alarmPanel;
        gp1 = graphPanel3;
        sp = searchPanel;
        gp2 = graphPanel4;
        sp.getList().setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarmPanel = new AlarmPanel();
        graphPanel3 = new GraphPanel();
        searchPanel = new SearchPanel();
        graphPanel4 = new GraphPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 10, 10));
        getContentPane().add(alarmPanel);
        getContentPane().add(graphPanel3);
        getContentPane().add(searchPanel);
        getContentPane().add(graphPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
                String server = "192.168.137.45";
		int port = 20001;
		int containerPort = 8094;
		containerClient = new ContainerClient(server, port, containerPort);
                Thread t = new Thread(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        MainFrame.containerClient.start();
                    }
                });
                
                
                
                
                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
        System.out.println("hey here is running okay?");
        t.start();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AlarmPanel alarmPanel;
    private GraphPanel graphPanel3;
    private GraphPanel graphPanel4;
    private SearchPanel searchPanel;
    // End of variables declaration//GEN-END:variables
}
